name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Priyangshu713
          outputs: |
            dist/github-snake.svg?palette=github&color_snake=%23ff6ad5&color_dots=%23fde7f7,%23f7b6ea,%23ef82db,%23dc56c8,%23bf2fb0
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23ff6ad5&color_dots=%23fde7f7,%23f7b6ea,%23ef82db,%23dc56c8,%23bf2fb0

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true
